version: '3.5'

networks:
  app-network:
    name: app-network
    driver: bridge


services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_ADMIN_LOGIN: ${DB_ADMIN_LOGIN}
        DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
        LHOST: ${LHOST}
        DB_CHARSET: ${DB_CHARSET}
    env_file:
      - .env
    volumes:
      - /home/eassamer/data/mysql:/db/mysql
    networks:
      - app-network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - /home/eassamer/data/wordpress:/var/www/html/
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
      - adminer
    volumes:
      - /home/eassamer/data/wordpress:/var/www/html/
      - /home/eassamer/data/adminer:/var/www/adminer/
    networks:
      - app-network
    restart: unless-stopped
  adminer:
    container_name: adminer
    build : ./requirements/bonus/adminer
    depends_on:
      - mariadb
    volumes:
      - /home/eassamer/data/adminer:/var/www/adminer/
    networks:
      - app-network
