CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'eassamer'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON wordpress.* TO 'eassamer'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1234';